// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Payment struct {
	ID            uuid.UUID          `json:"id"`
	OrderID       uuid.UUID          `json:"order_id"`
	Username      string             `json:"username"`
	Network       string             `json:"network"`
	Currency      string             `json:"currency"`
	Amount        float64            `json:"amount"`
	WalletAddress string             `json:"wallet_address"`
	TxHash        pgtype.Text        `json:"tx_hash"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type PaymentWallet struct {
	ID            int32              `json:"id"`
	Network       string             `json:"network"`
	WalletAddress string             `json:"wallet_address"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
