// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreatePaymentWallet(ctx context.Context, arg CreatePaymentWalletParams) (PaymentWallet, error)
	DeletePaymentWallet(ctx context.Context, network string) error
	GetPayment(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByTxHash(ctx context.Context, txHash pgtype.Text) (Payment, error)
	GetWalletAddressByNetwork(ctx context.Context, network string) (PaymentWallet, error)
	ListPaymentWallets(ctx context.Context) ([]PaymentWallet, error)
	ListPaymentsByUser(ctx context.Context, arg ListPaymentsByUserParams) ([]Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdatePaymentWallet(ctx context.Context, arg UpdatePaymentWalletParams) (PaymentWallet, error)
}

var _ Querier = (*Queries)(nil)
