// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Icon      string             `json:"icon"`
	UpdatedAt time.Time          `json:"updated_at"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ColorVarian struct {
	ID        int64              `json:"id"`
	ProductID int64              `json:"product_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Images    []string           `json:"images"`
	UpdatedAt time.Time          `json:"updated_at"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Product struct {
	ID          int64    `json:"id"`
	CategoryID  int64    `json:"category_id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Images      []string `json:"images"`
	Rating      float32  `json:"rating"`
	// must be positive
	Price     pgtype.Numeric     `json:"price"`
	UpdatedAt time.Time          `json:"updated_at"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type SizeVarian struct {
	ID            int64              `json:"id"`
	ColorVarianID int64              `json:"color_varian_id"`
	Size          string             `json:"size"`
	Stock         int64              `json:"stock"`
	UpdatedAt     time.Time          `json:"updated_at"`
	CreatedAt     time.Time          `json:"created_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}
