// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
)

type Querier interface {
	CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error)
	CreateColorVarianProduct(ctx context.Context, arg CreateColorVarianProductParams) (ColorVarian, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSizeVarianProduct(ctx context.Context, arg CreateSizeVarianProductParams) (SizeVarian, error)
	DeleteCategories(ctx context.Context, id int64) error
	DeleteColorVarianProduct(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteSizeVarianProduct(ctx context.Context, id int64) error
	GetCategories(ctx context.Context, id int64) (Category, error)
	GetCategoriesForUpdate(ctx context.Context, id int64) (Category, error)
	GetColorVarianProduct(ctx context.Context, id int64) (GetColorVarianProductRow, error)
	GetColorVarianProductForUpdate(ctx context.Context, id int64) (ColorVarian, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductForUpdate(ctx context.Context, id int64) (Product, error)
	GetProductWithDetail(ctx context.Context, id int64) (GetProductWithDetailRow, error)
	GetSizeVarianProduct(ctx context.Context, id int64) (SizeVarian, error)
	GetSizeVarianProductForUpdate(ctx context.Context, id int64) (SizeVarian, error)
	ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error)
	ListColorVarianProduct(ctx context.Context, arg ListColorVarianProductParams) ([]ListColorVarianProductRow, error)
	ListProduct(ctx context.Context, arg ListProductParams) ([]ListProductRow, error)
	ListSizeVarianProduct(ctx context.Context, arg ListSizeVarianProductParams) ([]SizeVarian, error)
	UpdateCategories(ctx context.Context, arg UpdateCategoriesParams) (Category, error)
	UpdateColorVarianProduct(ctx context.Context, arg UpdateColorVarianProductParams) (ColorVarian, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSizeVarianProduct(ctx context.Context, arg UpdateSizeVarianProductParams) (SizeVarian, error)
}

var _ Querier = (*Queries)(nil)
