// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: cars.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Transmission  string                 `protobuf:"bytes,7,opt,name=transmission,proto3" json:"transmission,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Location      string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	Price         float64                `protobuf:"fixed64,12,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency,omitempty"`
	IsSold        bool                   `protobuf:"varint,14,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Car) Reset() {
	*x = Car{}
	mi := &file_cars_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Car) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Car) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *Car) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *Car) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *Car) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *Car) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Car) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Car) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Car) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Car) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Car) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

func (x *Car) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Car) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,4,opt,name=year,proto3" json:"year,omitempty"`
	Mileage       int32                  `protobuf:"varint,5,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Transmission  string                 `protobuf:"bytes,6,opt,name=transmission,proto3" json:"transmission,omitempty"`
	FuelType      string                 `protobuf:"bytes,7,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Location      string                 `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,10,rep,name=images,proto3" json:"images,omitempty"`
	Price         float64                `protobuf:"fixed64,11,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,12,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCarRequest) Reset() {
	*x = CreateCarRequest{}
	mi := &file_cars_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCarRequest) ProtoMessage() {}

func (x *CreateCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCarRequest.ProtoReflect.Descriptor instead.
func (*CreateCarRequest) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCarRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *CreateCarRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *CreateCarRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *CreateCarRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *CreateCarRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *CreateCarRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *CreateCarRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CreateCarRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCarRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateCarRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateCarRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type UpdateCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Brand         string                 `protobuf:"bytes,3,opt,name=brand,proto3" json:"brand,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	Mileage       int32                  `protobuf:"varint,6,opt,name=mileage,proto3" json:"mileage,omitempty"`
	Transmission  string                 `protobuf:"bytes,7,opt,name=transmission,proto3" json:"transmission,omitempty"`
	FuelType      string                 `protobuf:"bytes,8,opt,name=fuel_type,json=fuelType,proto3" json:"fuel_type,omitempty"`
	Location      string                 `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,11,rep,name=images,proto3" json:"images,omitempty"`
	Price         float64                `protobuf:"fixed64,12,opt,name=price,proto3" json:"price,omitempty"`
	Currency      string                 `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency,omitempty"`
	IsSold        bool                   `protobuf:"varint,14,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCarRequest) Reset() {
	*x = UpdateCarRequest{}
	mi := &file_cars_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCarRequest) ProtoMessage() {}

func (x *UpdateCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCarRequest.ProtoReflect.Descriptor instead.
func (*UpdateCarRequest) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateCarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCarRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCarRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateCarRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *UpdateCarRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *UpdateCarRequest) GetMileage() int32 {
	if x != nil {
		return x.Mileage
	}
	return 0
}

func (x *UpdateCarRequest) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *UpdateCarRequest) GetFuelType() string {
	if x != nil {
		return x.FuelType
	}
	return ""
}

func (x *UpdateCarRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *UpdateCarRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCarRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateCarRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateCarRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateCarRequest) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

type GetCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCarRequest) Reset() {
	*x = GetCarRequest{}
	mi := &file_cars_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCarRequest) ProtoMessage() {}

func (x *GetCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCarRequest.ProtoReflect.Descriptor instead.
func (*GetCarRequest) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{3}
}

func (x *GetCarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCarRequest) Reset() {
	*x = DeleteCarRequest{}
	mi := &file_cars_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCarRequest) ProtoMessage() {}

func (x *DeleteCarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCarRequest.ProtoReflect.Descriptor instead.
func (*DeleteCarRequest) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCarRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCarsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`                 // jumlah per halaman
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`               // offset data (page * limit)
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`                // cari nama/brand/model
	Brand         string                 `protobuf:"bytes,4,opt,name=brand,proto3" json:"brand,omitempty"`                  // filter brand
	Location      string                 `protobuf:"bytes,5,opt,name=location,proto3" json:"location,omitempty"`            // filter lokasi
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`            // filter berdasarkan mata uang
	IsSold        bool                   `protobuf:"varint,7,opt,name=is_sold,json=isSold,proto3" json:"is_sold,omitempty"` // filter status terjual
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCarsRequest) Reset() {
	*x = ListCarsRequest{}
	mi := &file_cars_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsRequest) ProtoMessage() {}

func (x *ListCarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsRequest.ProtoReflect.Descriptor instead.
func (*ListCarsRequest) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{5}
}

func (x *ListCarsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCarsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCarsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListCarsRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *ListCarsRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ListCarsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ListCarsRequest) GetIsSold() bool {
	if x != nil {
		return x.IsSold
	}
	return false
}

type CarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Car           *Car                   `protobuf:"bytes,1,opt,name=car,proto3" json:"car,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarResponse) Reset() {
	*x = CarResponse{}
	mi := &file_cars_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarResponse) ProtoMessage() {}

func (x *CarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarResponse.ProtoReflect.Descriptor instead.
func (*CarResponse) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{6}
}

func (x *CarResponse) GetCar() *Car {
	if x != nil {
		return x.Car
	}
	return nil
}

type ListCarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cars          []*Car                 `protobuf:"bytes,1,rep,name=cars,proto3" json:"cars,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // total data (tanpa pagination)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCarsResponse) Reset() {
	*x = ListCarsResponse{}
	mi := &file_cars_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCarsResponse) ProtoMessage() {}

func (x *ListCarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCarsResponse.ProtoReflect.Descriptor instead.
func (*ListCarsResponse) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{7}
}

func (x *ListCarsResponse) GetCars() []*Car {
	if x != nil {
		return x.Cars
	}
	return nil
}

func (x *ListCarsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteCarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCarResponse) Reset() {
	*x = DeleteCarResponse{}
	mi := &file_cars_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCarResponse) ProtoMessage() {}

func (x *DeleteCarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cars_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCarResponse.ProtoReflect.Descriptor instead.
func (*DeleteCarResponse) Descriptor() ([]byte, []int) {
	return file_cars_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCarResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_cars_proto protoreflect.FileDescriptor

const file_cars_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"cars.proto\x12\x04cars\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdb\x03\n" +
	"\x03Car\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\"\n" +
	"\ftransmission\x18\a \x01(\tR\ftransmission\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\v \x03(\tR\x06images\x12\x14\n" +
	"\x05price\x18\f \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\r \x01(\tR\bcurrency\x12\x17\n" +
	"\ais_sold\x18\x0e \x01(\bR\x06isSold\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc9\x02\n" +
	"\x10CreateCarRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x04 \x01(\x05R\x04year\x12\x18\n" +
	"\amileage\x18\x05 \x01(\x05R\amileage\x12\"\n" +
	"\ftransmission\x18\x06 \x01(\tR\ftransmission\x12\x1b\n" +
	"\tfuel_type\x18\a \x01(\tR\bfuelType\x12\x1a\n" +
	"\blocation\x18\b \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\n" +
	" \x03(\tR\x06images\x12\x14\n" +
	"\x05price\x18\v \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\f \x01(\tR\bcurrency\"\xf2\x02\n" +
	"\x10UpdateCarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05brand\x18\x03 \x01(\tR\x05brand\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\x12\x18\n" +
	"\amileage\x18\x06 \x01(\x05R\amileage\x12\"\n" +
	"\ftransmission\x18\a \x01(\tR\ftransmission\x12\x1b\n" +
	"\tfuel_type\x18\b \x01(\tR\bfuelType\x12\x1a\n" +
	"\blocation\x18\t \x01(\tR\blocation\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\v \x03(\tR\x06images\x12\x14\n" +
	"\x05price\x18\f \x01(\x01R\x05price\x12\x1a\n" +
	"\bcurrency\x18\r \x01(\tR\bcurrency\x12\x17\n" +
	"\ais_sold\x18\x0e \x01(\bR\x06isSold\"\x1f\n" +
	"\rGetCarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10DeleteCarRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xbe\x01\n" +
	"\x0fListCarsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x14\n" +
	"\x05brand\x18\x04 \x01(\tR\x05brand\x12\x1a\n" +
	"\blocation\x18\x05 \x01(\tR\blocation\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x17\n" +
	"\ais_sold\x18\a \x01(\bR\x06isSold\"*\n" +
	"\vCarResponse\x12\x1b\n" +
	"\x03car\x18\x01 \x01(\v2\t.cars.CarR\x03car\"G\n" +
	"\x10ListCarsResponse\x12\x1d\n" +
	"\x04cars\x18\x01 \x03(\v2\t.cars.CarR\x04cars\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"-\n" +
	"\x11DeleteCarResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x9c\x03\n" +
	"\n" +
	"CarService\x12Q\n" +
	"\tCreateCar\x12\x16.cars.CreateCarRequest\x1a\x11.cars.CarResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/car/create\x12G\n" +
	"\x06GetCar\x12\x13.cars.GetCarRequest\x1a\x11.cars.CarResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/cars/{id}\x12K\n" +
	"\bListCars\x12\x15.cars.ListCarsRequest\x1a\x16.cars.ListCarsResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/v1/cars\x12Q\n" +
	"\tUpdateCar\x12\x16.cars.UpdateCarRequest\x1a\x11.cars.CarResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/car/update\x12R\n" +
	"\tDeleteCar\x12\x16.cars.DeleteCarRequest\x1a\x17.cars.DeleteCarResponse\"\x14\x82\xd3\xe4\x93\x02\x0e*\f/v1/car/{id}B-Z+e-commerce-microservice/proto-shared/gen/pbb\x06proto3"

var (
	file_cars_proto_rawDescOnce sync.Once
	file_cars_proto_rawDescData []byte
)

func file_cars_proto_rawDescGZIP() []byte {
	file_cars_proto_rawDescOnce.Do(func() {
		file_cars_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cars_proto_rawDesc), len(file_cars_proto_rawDesc)))
	})
	return file_cars_proto_rawDescData
}

var file_cars_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_cars_proto_goTypes = []any{
	(*Car)(nil),                   // 0: cars.Car
	(*CreateCarRequest)(nil),      // 1: cars.CreateCarRequest
	(*UpdateCarRequest)(nil),      // 2: cars.UpdateCarRequest
	(*GetCarRequest)(nil),         // 3: cars.GetCarRequest
	(*DeleteCarRequest)(nil),      // 4: cars.DeleteCarRequest
	(*ListCarsRequest)(nil),       // 5: cars.ListCarsRequest
	(*CarResponse)(nil),           // 6: cars.CarResponse
	(*ListCarsResponse)(nil),      // 7: cars.ListCarsResponse
	(*DeleteCarResponse)(nil),     // 8: cars.DeleteCarResponse
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_cars_proto_depIdxs = []int32{
	9, // 0: cars.Car.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: cars.Car.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: cars.CarResponse.car:type_name -> cars.Car
	0, // 3: cars.ListCarsResponse.cars:type_name -> cars.Car
	1, // 4: cars.CarService.CreateCar:input_type -> cars.CreateCarRequest
	3, // 5: cars.CarService.GetCar:input_type -> cars.GetCarRequest
	5, // 6: cars.CarService.ListCars:input_type -> cars.ListCarsRequest
	2, // 7: cars.CarService.UpdateCar:input_type -> cars.UpdateCarRequest
	4, // 8: cars.CarService.DeleteCar:input_type -> cars.DeleteCarRequest
	6, // 9: cars.CarService.CreateCar:output_type -> cars.CarResponse
	6, // 10: cars.CarService.GetCar:output_type -> cars.CarResponse
	7, // 11: cars.CarService.ListCars:output_type -> cars.ListCarsResponse
	6, // 12: cars.CarService.UpdateCar:output_type -> cars.CarResponse
	8, // 13: cars.CarService.DeleteCar:output_type -> cars.DeleteCarResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cars_proto_init() }
func file_cars_proto_init() {
	if File_cars_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cars_proto_rawDesc), len(file_cars_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cars_proto_goTypes,
		DependencyIndexes: file_cars_proto_depIdxs,
		MessageInfos:      file_cars_proto_msgTypes,
	}.Build()
	File_cars_proto = out.File
	file_cars_proto_goTypes = nil
	file_cars_proto_depIdxs = nil
}
