// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: user.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Representasi pengguna (berdasarkan tabel `users`)
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Representasi alamat pengguna (tabel `user_addresses`)
type UserAddress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Label          string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	RecipientName  string                 `protobuf:"bytes,4,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientPhone string                 `protobuf:"bytes,5,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	AddressLine    string                 `protobuf:"bytes,6,opt,name=address_line,json=addressLine,proto3" json:"address_line,omitempty"`
	City           string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Province       string                 `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	PostalCode     string                 `protobuf:"bytes,9,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	IsSelected     bool                   `protobuf:"varint,10,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserAddress) Reset() {
	*x = UserAddress{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddress) ProtoMessage() {}

func (x *UserAddress) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddress.ProtoReflect.Descriptor instead.
func (*UserAddress) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserAddress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserAddress) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserAddress) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UserAddress) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *UserAddress) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *UserAddress) GetAddressLine() string {
	if x != nil {
		return x.AddressLine
	}
	return ""
}

func (x *UserAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserAddress) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UserAddress) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

func (x *UserAddress) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserAddress) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName      string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateUserRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Username       string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Label          string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	RecipientName  string                 `protobuf:"bytes,3,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientPhone string                 `protobuf:"bytes,4,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	AddressLine    string                 `protobuf:"bytes,5,opt,name=address_line,json=addressLine,proto3" json:"address_line,omitempty"`
	City           string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Province       string                 `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	PostalCode     string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAddressRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAddressRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *CreateAddressRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *CreateAddressRequest) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *CreateAddressRequest) GetAddressLine() string {
	if x != nil {
		return x.AddressLine
	}
	return ""
}

func (x *CreateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CreateAddressRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CreateAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type UpdateAddressRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label          string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	RecipientName  string                 `protobuf:"bytes,3,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientPhone string                 `protobuf:"bytes,4,opt,name=recipient_phone,json=recipientPhone,proto3" json:"recipient_phone,omitempty"`
	AddressLine    string                 `protobuf:"bytes,5,opt,name=address_line,json=addressLine,proto3" json:"address_line,omitempty"`
	City           string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	Province       string                 `protobuf:"bytes,7,opt,name=province,proto3" json:"province,omitempty"`
	PostalCode     string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	IsSelected     bool                   `protobuf:"varint,9,opt,name=is_selected,json=isSelected,proto3" json:"is_selected,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAddressRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *UpdateAddressRequest) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *UpdateAddressRequest) GetRecipientPhone() string {
	if x != nil {
		return x.RecipientPhone
	}
	return ""
}

func (x *UpdateAddressRequest) GetAddressLine() string {
	if x != nil {
		return x.AddressLine
	}
	return ""
}

func (x *UpdateAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateAddressRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UpdateAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UpdateAddressRequest) GetIsSelected() bool {
	if x != nil {
		return x.IsSelected
	}
	return false
}

type GetUserAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserAddressesRequest) Reset() {
	*x = GetUserAddressesRequest{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAddressesRequest) ProtoMessage() {}

func (x *GetUserAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAddressesRequest.ProtoReflect.Descriptor instead.
func (*GetUserAddressesRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserAddressesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type UserAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*UserAddress         `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddressesResponse) Reset() {
	*x = UserAddressesResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddressesResponse) ProtoMessage() {}

func (x *UserAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddressesResponse.ProtoReflect.Descriptor instead.
func (*UserAddressesResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UserAddressesResponse) GetAddresses() []*UserAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type UserAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *UserAddress           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAddressResponse) Reset() {
	*x = UserAddressResponse{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAddressResponse) ProtoMessage() {}

func (x *UserAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAddressResponse.ProtoReflect.Descriptor instead.
func (*UserAddressResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UserAddressResponse) GetAddress() *UserAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

type EmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResponse) Reset() {
	*x = EmptyResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResponse) ProtoMessage() {}

func (x *EmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResponse.ProtoReflect.Descriptor instead.
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd8\x01\n" +
	"\x04User\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaa\x03\n" +
	"\vUserAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12%\n" +
	"\x0erecipient_name\x18\x04 \x01(\tR\rrecipientName\x12'\n" +
	"\x0frecipient_phone\x18\x05 \x01(\tR\x0erecipientPhone\x12!\n" +
	"\faddress_line\x18\x06 \x01(\tR\vaddressLine\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\b \x01(\tR\bprovince\x12\x1f\n" +
	"\vpostal_code\x18\t \x01(\tR\n" +
	"postalCode\x12\x1f\n" +
	"\vis_selected\x18\n" +
	" \x01(\bR\n" +
	"isSelected\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"o\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12!\n" +
	"\fphone_number\x18\x03 \x01(\tR\vphoneNumber\",\n" +
	"\x0eGetUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"\x8c\x02\n" +
	"\x14CreateAddressRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12%\n" +
	"\x0erecipient_name\x18\x03 \x01(\tR\rrecipientName\x12'\n" +
	"\x0frecipient_phone\x18\x04 \x01(\tR\x0erecipientPhone\x12!\n" +
	"\faddress_line\x18\x05 \x01(\tR\vaddressLine\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\a \x01(\tR\bprovince\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\"\xa1\x02\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12%\n" +
	"\x0erecipient_name\x18\x03 \x01(\tR\rrecipientName\x12'\n" +
	"\x0frecipient_phone\x18\x04 \x01(\tR\x0erecipientPhone\x12!\n" +
	"\faddress_line\x18\x05 \x01(\tR\vaddressLine\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x1a\n" +
	"\bprovince\x18\a \x01(\tR\bprovince\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\x12\x1f\n" +
	"\vis_selected\x18\t \x01(\bR\n" +
	"isSelected\"5\n" +
	"\x17GetUserAddressesRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\".\n" +
	"\fUserResponse\x12\x1e\n" +
	"\x04user\x18\x01 \x01(\v2\n" +
	".user.UserR\x04user\"H\n" +
	"\x15UserAddressesResponse\x12/\n" +
	"\taddresses\x18\x01 \x03(\v2\x11.user.UserAddressR\taddresses\"B\n" +
	"\x13UserAddressResponse\x12+\n" +
	"\aaddress\x18\x01 \x01(\v2\x11.user.UserAddressR\aaddress\"\x0f\n" +
	"\rEmptyResponse2\xef\x03\n" +
	"\vUserService\x12U\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/user/create\x12H\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/user/me\x12j\n" +
	"\rCreateAddress\x12\x1a.user.CreateAddressRequest\x1a\x19.user.UserAddressResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/user/address/create\x12j\n" +
	"\rUpdateAddress\x12\x1a.user.UpdateAddressRequest\x1a\x19.user.UserAddressResponse\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/v1/user/address/update\x12g\n" +
	"\fGetAddresses\x12\x1d.user.GetUserAddressesRequest\x1a\x1b.user.UserAddressesResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/user/addressessB-Z+e-commerce-microservice/proto-shared/gen/pbb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_user_proto_goTypes = []any{
	(*User)(nil),                    // 0: user.User
	(*UserAddress)(nil),             // 1: user.UserAddress
	(*CreateUserRequest)(nil),       // 2: user.CreateUserRequest
	(*GetUserRequest)(nil),          // 3: user.GetUserRequest
	(*CreateAddressRequest)(nil),    // 4: user.CreateAddressRequest
	(*UpdateAddressRequest)(nil),    // 5: user.UpdateAddressRequest
	(*GetUserAddressesRequest)(nil), // 6: user.GetUserAddressesRequest
	(*UserResponse)(nil),            // 7: user.UserResponse
	(*UserAddressesResponse)(nil),   // 8: user.UserAddressesResponse
	(*UserAddressResponse)(nil),     // 9: user.UserAddressResponse
	(*EmptyResponse)(nil),           // 10: user.EmptyResponse
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
}
var file_user_proto_depIdxs = []int32{
	11, // 0: user.User.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: user.User.updated_at:type_name -> google.protobuf.Timestamp
	11, // 2: user.UserAddress.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: user.UserAddress.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: user.UserResponse.user:type_name -> user.User
	1,  // 5: user.UserAddressesResponse.addresses:type_name -> user.UserAddress
	1,  // 6: user.UserAddressResponse.address:type_name -> user.UserAddress
	2,  // 7: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	3,  // 8: user.UserService.GetUser:input_type -> user.GetUserRequest
	4,  // 9: user.UserService.CreateAddress:input_type -> user.CreateAddressRequest
	5,  // 10: user.UserService.UpdateAddress:input_type -> user.UpdateAddressRequest
	6,  // 11: user.UserService.GetAddresses:input_type -> user.GetUserAddressesRequest
	7,  // 12: user.UserService.CreateUser:output_type -> user.UserResponse
	7,  // 13: user.UserService.GetUser:output_type -> user.UserResponse
	9,  // 14: user.UserService.CreateAddress:output_type -> user.UserAddressResponse
	9,  // 15: user.UserService.UpdateAddress:output_type -> user.UserAddressResponse
	8,  // 16: user.UserService.GetAddresses:output_type -> user.UserAddressesResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
