// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/pb/product.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_internal_pb_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{0}
}

func (x *Category) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Category) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Category) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SizeVarian struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ColorVarianId int64                  `protobuf:"varint,2,opt,name=color_varian_id,json=colorVarianId,proto3" json:"color_varian_id,omitempty"`
	Size          string                 `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	Stock         int64                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeVarian) Reset() {
	*x = SizeVarian{}
	mi := &file_internal_pb_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeVarian) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeVarian) ProtoMessage() {}

func (x *SizeVarian) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeVarian.ProtoReflect.Descriptor instead.
func (*SizeVarian) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{1}
}

func (x *SizeVarian) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SizeVarian) GetColorVarianId() int64 {
	if x != nil {
		return x.ColorVarianId
	}
	return 0
}

func (x *SizeVarian) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *SizeVarian) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SizeVarian) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SizeVarian) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ColorVarian struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProductId int64                  `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name      string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Color     string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	Images    []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Nested size varians
	SizeVarians   []*SizeVarian `protobuf:"bytes,8,rep,name=size_varians,json=sizeVarians,proto3" json:"size_varians,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorVarian) Reset() {
	*x = ColorVarian{}
	mi := &file_internal_pb_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorVarian) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorVarian) ProtoMessage() {}

func (x *ColorVarian) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorVarian.ProtoReflect.Descriptor instead.
func (*ColorVarian) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{2}
}

func (x *ColorVarian) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ColorVarian) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ColorVarian) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ColorVarian) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ColorVarian) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ColorVarian) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ColorVarian) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ColorVarian) GetSizeVarians() []*SizeVarian {
	if x != nil {
		return x.SizeVarians
	}
	return nil
}

type ProductDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Rating        float32                `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Category      *Category              `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	ColorVarians  []*ColorVarian         `protobuf:"bytes,11,rep,name=color_varians,json=colorVarians,proto3" json:"color_varians,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductDetail) Reset() {
	*x = ProductDetail{}
	mi := &file_internal_pb_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductDetail) ProtoMessage() {}

func (x *ProductDetail) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductDetail.ProtoReflect.Descriptor instead.
func (*ProductDetail) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{3}
}

func (x *ProductDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProductDetail) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProductDetail) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductDetail) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductDetail) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ProductDetail) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ProductDetail) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProductDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ProductDetail) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ProductDetail) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *ProductDetail) GetColorVarians() []*ColorVarian {
	if x != nil {
		return x.ColorVarians
	}
	return nil
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,5,rep,name=images,proto3" json:"images,omitempty"`
	Rating        float32                `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Price         float64                `protobuf:"fixed64,7,opt,name=price,proto3" json:"price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Category      *Category              `protobuf:"bytes,10,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_internal_pb_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Product) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Product) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,2,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCategoryRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type CreateProductRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	CategoryId    int64                       `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string                    `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Price         float64                     `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	ColorVarians  []*CreateColorVarianRequest `protobuf:"bytes,6,rep,name=color_varians,json=colorVarians,proto3" json:"color_varians,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetColorVarians() []*CreateColorVarianRequest {
	if x != nil {
		return x.ColorVarians
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Images        []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateProductRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *UpdateProductRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreateColorVarianRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	ProductId     int64                      `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                     `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Images        []string                   `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	SizeVarians   []*CreateSizeVarianRequest `protobuf:"bytes,8,rep,name=size_varians,json=sizeVarians,proto3" json:"size_varians,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateColorVarianRequest) Reset() {
	*x = CreateColorVarianRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateColorVarianRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateColorVarianRequest) ProtoMessage() {}

func (x *CreateColorVarianRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateColorVarianRequest.ProtoReflect.Descriptor instead.
func (*CreateColorVarianRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{9}
}

func (x *CreateColorVarianRequest) GetProductId() int64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateColorVarianRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateColorVarianRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateColorVarianRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateColorVarianRequest) GetSizeVarians() []*CreateSizeVarianRequest {
	if x != nil {
		return x.SizeVarians
	}
	return nil
}

type UpdateColorVarianRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Images        []string               `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateColorVarianRequest) Reset() {
	*x = UpdateColorVarianRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateColorVarianRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateColorVarianRequest) ProtoMessage() {}

func (x *UpdateColorVarianRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateColorVarianRequest.ProtoReflect.Descriptor instead.
func (*UpdateColorVarianRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateColorVarianRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateColorVarianRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateColorVarianRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *UpdateColorVarianRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateSizeVarianRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColorVarianId int64                  `protobuf:"varint,1,opt,name=color_varian_id,json=colorVarianId,proto3" json:"color_varian_id,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSizeVarianRequest) Reset() {
	*x = CreateSizeVarianRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSizeVarianRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSizeVarianRequest) ProtoMessage() {}

func (x *CreateSizeVarianRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSizeVarianRequest.ProtoReflect.Descriptor instead.
func (*CreateSizeVarianRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{11}
}

func (x *CreateSizeVarianRequest) GetColorVarianId() int64 {
	if x != nil {
		return x.ColorVarianId
	}
	return 0
}

func (x *CreateSizeVarianRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *CreateSizeVarianRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type UpdateSizeVarianRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          string                 `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Stock         int64                  `protobuf:"varint,3,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSizeVarianRequest) Reset() {
	*x = UpdateSizeVarianRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSizeVarianRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSizeVarianRequest) ProtoMessage() {}

func (x *UpdateSizeVarianRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSizeVarianRequest.ProtoReflect.Descriptor instead.
func (*UpdateSizeVarianRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSizeVarianRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateSizeVarianRequest) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *UpdateSizeVarianRequest) GetStock() int64 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type GetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByIDRequest) Reset() {
	*x = GetByIDRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByIDRequest) ProtoMessage() {}

func (x *GetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{13}
}

func (x *GetByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PaginationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // halaman saat ini
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // jumlah item per halaman
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationRequest) Reset() {
	*x = PaginationRequest{}
	mi := &file_internal_pb_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationRequest) ProtoMessage() {}

func (x *PaginationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationRequest.ProtoReflect.Descriptor instead.
func (*PaginationRequest) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{14}
}

func (x *PaginationRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PaginationRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type CategoryList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryList) Reset() {
	*x = CategoryList{}
	mi := &file_internal_pb_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryList) ProtoMessage() {}

func (x *CategoryList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryList.ProtoReflect.Descriptor instead.
func (*CategoryList) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{15}
}

func (x *CategoryList) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

type ProductList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	TotalPages    int32                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	TotalItems    int64                  `protobuf:"varint,5,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductList) Reset() {
	*x = ProductList{}
	mi := &file_internal_pb_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductList) ProtoMessage() {}

func (x *ProductList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductList.ProtoReflect.Descriptor instead.
func (*ProductList) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{16}
}

func (x *ProductList) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ProductList) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ProductList) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ProductList) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

func (x *ProductList) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

type ColorVarianList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ColorVarians  []*ColorVarian         `protobuf:"bytes,1,rep,name=color_varians,json=colorVarians,proto3" json:"color_varians,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ColorVarianList) Reset() {
	*x = ColorVarianList{}
	mi := &file_internal_pb_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ColorVarianList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColorVarianList) ProtoMessage() {}

func (x *ColorVarianList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColorVarianList.ProtoReflect.Descriptor instead.
func (*ColorVarianList) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{17}
}

func (x *ColorVarianList) GetColorVarians() []*ColorVarian {
	if x != nil {
		return x.ColorVarians
	}
	return nil
}

type SizeVarianList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SizeVarians   []*SizeVarian          `protobuf:"bytes,1,rep,name=size_varians,json=sizeVarians,proto3" json:"size_varians,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SizeVarianList) Reset() {
	*x = SizeVarianList{}
	mi := &file_internal_pb_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SizeVarianList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SizeVarianList) ProtoMessage() {}

func (x *SizeVarianList) ProtoReflect() protoreflect.Message {
	mi := &file_internal_pb_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SizeVarianList.ProtoReflect.Descriptor instead.
func (*SizeVarianList) Descriptor() ([]byte, []int) {
	return file_internal_pb_product_proto_rawDescGZIP(), []int{18}
}

func (x *SizeVarianList) GetSizeVarians() []*SizeVarian {
	if x != nil {
		return x.SizeVarians
	}
	return nil
}

var File_internal_pb_product_proto protoreflect.FileDescriptor

const file_internal_pb_product_proto_rawDesc = "" +
	"\n" +
	"\x19internal/pb/product.proto\x12\aproduct\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb8\x01\n" +
	"\bCategory\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe4\x01\n" +
	"\n" +
	"SizeVarian\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0fcolor_varian_id\x18\x02 \x01(\x03R\rcolorVarianId\x12\x12\n" +
	"\x04size\x18\x03 \x01(\tR\x04size\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x03R\x05stock\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xac\x02\n" +
	"\vColorVarian\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x126\n" +
	"\fsize_varians\x18\b \x03(\v2\x13.product.SizeVarianR\vsizeVarians\"\x9c\x03\n" +
	"\rProductDetail\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x02R\x06rating\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12-\n" +
	"\bcategory\x18\n" +
	" \x01(\v2\x11.product.CategoryR\bcategory\x129\n" +
	"\rcolor_varians\x18\v \x03(\v2\x14.product.ColorVarianR\fcolorVarians\"\xdb\x02\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x05 \x03(\tR\x06images\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x02R\x06rating\x12\x14\n" +
	"\x05price\x18\a \x01(\x01R\x05price\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12-\n" +
	"\bcategory\x18\n" +
	" \x01(\v2\x11.product.CategoryR\bcategory\"?\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x02 \x01(\tR\x04icon\"O\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\"\xe3\x01\n" +
	"\x14CreateProductRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12F\n" +
	"\rcolor_varians\x18\x06 \x03(\v2!.product.CreateColorVarianRequestR\fcolorVarians\"\x8a\x01\n" +
	"\x14UpdateProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\"\xc0\x01\n" +
	"\x18CreateColorVarianRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x03R\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x12C\n" +
	"\fsize_varians\x18\b \x03(\v2 .product.CreateSizeVarianRequestR\vsizeVarians\"l\n" +
	"\x18UpdateColorVarianRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\"k\n" +
	"\x17CreateSizeVarianRequest\x12&\n" +
	"\x0fcolor_varian_id\x18\x01 \x01(\x03R\rcolorVarianId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\"S\n" +
	"\x17UpdateSizeVarianRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\tR\x04size\x12\x14\n" +
	"\x05stock\x18\x03 \x01(\x03R\x05stock\" \n" +
	"\x0eGetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x11PaginationRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"A\n" +
	"\fCategoryList\x121\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x11.product.CategoryR\n" +
	"categories\"\xae\x01\n" +
	"\vProductList\x12,\n" +
	"\bproducts\x18\x01 \x03(\v2\x10.product.ProductR\bproducts\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x05R\n" +
	"totalPages\x12\x1f\n" +
	"\vtotal_items\x18\x05 \x01(\x03R\n" +
	"totalItems\"L\n" +
	"\x0fColorVarianList\x129\n" +
	"\rcolor_varians\x18\x01 \x03(\v2\x14.product.ColorVarianR\fcolorVarians\"H\n" +
	"\x0eSizeVarianList\x126\n" +
	"\fsize_varians\x18\x01 \x03(\v2\x13.product.SizeVarianR\vsizeVarians2\xe9\n" +
	"\n" +
	"\x0eProductService\x12C\n" +
	"\x0eCreateCategory\x12\x1e.product.CreateCategoryRequest\x1a\x11.product.Category\x129\n" +
	"\vGetCategory\x12\x17.product.GetByIDRequest\x1a\x11.product.Category\x12?\n" +
	"\x0eListCategories\x12\x16.google.protobuf.Empty\x1a\x15.product.CategoryList\x12C\n" +
	"\x0eUpdateCategory\x12\x1e.product.UpdateCategoryRequest\x1a\x11.product.Category\x12A\n" +
	"\x0eDeleteCategory\x12\x17.product.GetByIDRequest\x1a\x16.google.protobuf.Empty\x12@\n" +
	"\rCreateProduct\x12\x1d.product.CreateProductRequest\x1a\x10.product.Product\x12=\n" +
	"\n" +
	"GetProduct\x12\x17.product.GetByIDRequest\x1a\x16.product.ProductDetail\x12@\n" +
	"\fListProducts\x12\x1a.product.PaginationRequest\x1a\x14.product.ProductList\x12@\n" +
	"\rUpdateProduct\x12\x1d.product.UpdateProductRequest\x1a\x10.product.Product\x12@\n" +
	"\rDeleteProduct\x12\x17.product.GetByIDRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x11CreateColorVarian\x12!.product.CreateColorVarianRequest\x1a\x14.product.ColorVarian\x12?\n" +
	"\x0eGetColorVarian\x12\x17.product.GetByIDRequest\x1a\x14.product.ColorVarian\x12E\n" +
	"\x10ListColorVarians\x12\x17.product.GetByIDRequest\x1a\x18.product.ColorVarianList\x12L\n" +
	"\x11UpdateColorVarian\x12!.product.UpdateColorVarianRequest\x1a\x14.product.ColorVarian\x12D\n" +
	"\x11DeleteColorVarian\x12\x17.product.GetByIDRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x10CreateSizeVarian\x12 .product.CreateSizeVarianRequest\x1a\x13.product.SizeVarian\x12=\n" +
	"\rGetSizeVarian\x12\x17.product.GetByIDRequest\x1a\x13.product.SizeVarian\x12C\n" +
	"\x0fListSizeVarians\x12\x17.product.GetByIDRequest\x1a\x17.product.SizeVarianList\x12I\n" +
	"\x10UpdateSizeVarian\x12 .product.UpdateSizeVarianRequest\x1a\x13.product.SizeVarian\x12C\n" +
	"\x10DeleteSizeVarian\x12\x17.product.GetByIDRequest\x1a\x16.google.protobuf.EmptyB\x0fZ\r./internal/pbb\x06proto3"

var (
	file_internal_pb_product_proto_rawDescOnce sync.Once
	file_internal_pb_product_proto_rawDescData []byte
)

func file_internal_pb_product_proto_rawDescGZIP() []byte {
	file_internal_pb_product_proto_rawDescOnce.Do(func() {
		file_internal_pb_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_pb_product_proto_rawDesc), len(file_internal_pb_product_proto_rawDesc)))
	})
	return file_internal_pb_product_proto_rawDescData
}

var file_internal_pb_product_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_pb_product_proto_goTypes = []any{
	(*Category)(nil),                 // 0: product.Category
	(*SizeVarian)(nil),               // 1: product.SizeVarian
	(*ColorVarian)(nil),              // 2: product.ColorVarian
	(*ProductDetail)(nil),            // 3: product.ProductDetail
	(*Product)(nil),                  // 4: product.Product
	(*CreateCategoryRequest)(nil),    // 5: product.CreateCategoryRequest
	(*UpdateCategoryRequest)(nil),    // 6: product.UpdateCategoryRequest
	(*CreateProductRequest)(nil),     // 7: product.CreateProductRequest
	(*UpdateProductRequest)(nil),     // 8: product.UpdateProductRequest
	(*CreateColorVarianRequest)(nil), // 9: product.CreateColorVarianRequest
	(*UpdateColorVarianRequest)(nil), // 10: product.UpdateColorVarianRequest
	(*CreateSizeVarianRequest)(nil),  // 11: product.CreateSizeVarianRequest
	(*UpdateSizeVarianRequest)(nil),  // 12: product.UpdateSizeVarianRequest
	(*GetByIDRequest)(nil),           // 13: product.GetByIDRequest
	(*PaginationRequest)(nil),        // 14: product.PaginationRequest
	(*CategoryList)(nil),             // 15: product.CategoryList
	(*ProductList)(nil),              // 16: product.ProductList
	(*ColorVarianList)(nil),          // 17: product.ColorVarianList
	(*SizeVarianList)(nil),           // 18: product.SizeVarianList
	(*timestamppb.Timestamp)(nil),    // 19: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 20: google.protobuf.Empty
}
var file_internal_pb_product_proto_depIdxs = []int32{
	19, // 0: product.Category.created_at:type_name -> google.protobuf.Timestamp
	19, // 1: product.Category.updated_at:type_name -> google.protobuf.Timestamp
	19, // 2: product.SizeVarian.created_at:type_name -> google.protobuf.Timestamp
	19, // 3: product.SizeVarian.updated_at:type_name -> google.protobuf.Timestamp
	19, // 4: product.ColorVarian.created_at:type_name -> google.protobuf.Timestamp
	19, // 5: product.ColorVarian.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 6: product.ColorVarian.size_varians:type_name -> product.SizeVarian
	19, // 7: product.ProductDetail.created_at:type_name -> google.protobuf.Timestamp
	19, // 8: product.ProductDetail.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 9: product.ProductDetail.category:type_name -> product.Category
	2,  // 10: product.ProductDetail.color_varians:type_name -> product.ColorVarian
	19, // 11: product.Product.created_at:type_name -> google.protobuf.Timestamp
	19, // 12: product.Product.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 13: product.Product.category:type_name -> product.Category
	9,  // 14: product.CreateProductRequest.color_varians:type_name -> product.CreateColorVarianRequest
	11, // 15: product.CreateColorVarianRequest.size_varians:type_name -> product.CreateSizeVarianRequest
	0,  // 16: product.CategoryList.categories:type_name -> product.Category
	4,  // 17: product.ProductList.products:type_name -> product.Product
	2,  // 18: product.ColorVarianList.color_varians:type_name -> product.ColorVarian
	1,  // 19: product.SizeVarianList.size_varians:type_name -> product.SizeVarian
	5,  // 20: product.ProductService.CreateCategory:input_type -> product.CreateCategoryRequest
	13, // 21: product.ProductService.GetCategory:input_type -> product.GetByIDRequest
	20, // 22: product.ProductService.ListCategories:input_type -> google.protobuf.Empty
	6,  // 23: product.ProductService.UpdateCategory:input_type -> product.UpdateCategoryRequest
	13, // 24: product.ProductService.DeleteCategory:input_type -> product.GetByIDRequest
	7,  // 25: product.ProductService.CreateProduct:input_type -> product.CreateProductRequest
	13, // 26: product.ProductService.GetProduct:input_type -> product.GetByIDRequest
	14, // 27: product.ProductService.ListProducts:input_type -> product.PaginationRequest
	8,  // 28: product.ProductService.UpdateProduct:input_type -> product.UpdateProductRequest
	13, // 29: product.ProductService.DeleteProduct:input_type -> product.GetByIDRequest
	9,  // 30: product.ProductService.CreateColorVarian:input_type -> product.CreateColorVarianRequest
	13, // 31: product.ProductService.GetColorVarian:input_type -> product.GetByIDRequest
	13, // 32: product.ProductService.ListColorVarians:input_type -> product.GetByIDRequest
	10, // 33: product.ProductService.UpdateColorVarian:input_type -> product.UpdateColorVarianRequest
	13, // 34: product.ProductService.DeleteColorVarian:input_type -> product.GetByIDRequest
	11, // 35: product.ProductService.CreateSizeVarian:input_type -> product.CreateSizeVarianRequest
	13, // 36: product.ProductService.GetSizeVarian:input_type -> product.GetByIDRequest
	13, // 37: product.ProductService.ListSizeVarians:input_type -> product.GetByIDRequest
	12, // 38: product.ProductService.UpdateSizeVarian:input_type -> product.UpdateSizeVarianRequest
	13, // 39: product.ProductService.DeleteSizeVarian:input_type -> product.GetByIDRequest
	0,  // 40: product.ProductService.CreateCategory:output_type -> product.Category
	0,  // 41: product.ProductService.GetCategory:output_type -> product.Category
	15, // 42: product.ProductService.ListCategories:output_type -> product.CategoryList
	0,  // 43: product.ProductService.UpdateCategory:output_type -> product.Category
	20, // 44: product.ProductService.DeleteCategory:output_type -> google.protobuf.Empty
	4,  // 45: product.ProductService.CreateProduct:output_type -> product.Product
	3,  // 46: product.ProductService.GetProduct:output_type -> product.ProductDetail
	16, // 47: product.ProductService.ListProducts:output_type -> product.ProductList
	4,  // 48: product.ProductService.UpdateProduct:output_type -> product.Product
	20, // 49: product.ProductService.DeleteProduct:output_type -> google.protobuf.Empty
	2,  // 50: product.ProductService.CreateColorVarian:output_type -> product.ColorVarian
	2,  // 51: product.ProductService.GetColorVarian:output_type -> product.ColorVarian
	17, // 52: product.ProductService.ListColorVarians:output_type -> product.ColorVarianList
	2,  // 53: product.ProductService.UpdateColorVarian:output_type -> product.ColorVarian
	20, // 54: product.ProductService.DeleteColorVarian:output_type -> google.protobuf.Empty
	1,  // 55: product.ProductService.CreateSizeVarian:output_type -> product.SizeVarian
	1,  // 56: product.ProductService.GetSizeVarian:output_type -> product.SizeVarian
	18, // 57: product.ProductService.ListSizeVarians:output_type -> product.SizeVarianList
	1,  // 58: product.ProductService.UpdateSizeVarian:output_type -> product.SizeVarian
	20, // 59: product.ProductService.DeleteSizeVarian:output_type -> google.protobuf.Empty
	40, // [40:60] is the sub-list for method output_type
	20, // [20:40] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_pb_product_proto_init() }
func file_internal_pb_product_proto_init() {
	if File_internal_pb_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_pb_product_proto_rawDesc), len(file_internal_pb_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_pb_product_proto_goTypes,
		DependencyIndexes: file_internal_pb_product_proto_depIdxs,
		MessageInfos:      file_internal_pb_product_proto_msgTypes,
	}.Build()
	File_internal_pb_product_proto = out.File
	file_internal_pb_product_proto_goTypes = nil
	file_internal_pb_product_proto_depIdxs = nil
}
