// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: payment_wallet.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentWallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Network       string                 `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	WalletAddress string                 `protobuf:"bytes,3,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentWallet) Reset() {
	*x = PaymentWallet{}
	mi := &file_payment_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentWallet) ProtoMessage() {}

func (x *PaymentWallet) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentWallet.ProtoReflect.Descriptor instead.
func (*PaymentWallet) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{0}
}

func (x *PaymentWallet) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PaymentWallet) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *PaymentWallet) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *PaymentWallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreatePaymentWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentWalletRequest) Reset() {
	*x = CreatePaymentWalletRequest{}
	mi := &file_payment_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentWalletRequest) ProtoMessage() {}

func (x *CreatePaymentWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentWalletRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentWalletRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *CreatePaymentWalletRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type DeletePaymentWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentWalletResponse) Reset() {
	*x = DeletePaymentWalletResponse{}
	mi := &file_payment_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentWalletResponse) ProtoMessage() {}

func (x *DeletePaymentWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentWalletResponse.ProtoReflect.Descriptor instead.
func (*DeletePaymentWalletResponse) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{2}
}

func (x *DeletePaymentWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListPaymentWalletsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentWalletsRequest) Reset() {
	*x = ListPaymentWalletsRequest{}
	mi := &file_payment_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentWalletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentWalletsRequest) ProtoMessage() {}

func (x *ListPaymentWalletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentWalletsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentWalletsRequest) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{3}
}

type ListPaymentWalletsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*PaymentWallet       `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentWalletsResponse) Reset() {
	*x = ListPaymentWalletsResponse{}
	mi := &file_payment_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentWalletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentWalletsResponse) ProtoMessage() {}

func (x *ListPaymentWalletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentWalletsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentWalletsResponse) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *ListPaymentWalletsResponse) GetWallets() []*PaymentWallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

type UpdatePaymentWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentWalletRequest) Reset() {
	*x = UpdatePaymentWalletRequest{}
	mi := &file_payment_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentWalletRequest) ProtoMessage() {}

func (x *UpdatePaymentWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentWalletRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePaymentWalletRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *UpdatePaymentWalletRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type GetPaymentWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentWalletRequest) Reset() {
	*x = GetPaymentWalletRequest{}
	mi := &file_payment_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentWalletRequest) ProtoMessage() {}

func (x *GetPaymentWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentWalletRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *GetPaymentWalletRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type DeletePaymentWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePaymentWalletRequest) Reset() {
	*x = DeletePaymentWalletRequest{}
	mi := &file_payment_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePaymentWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentWalletRequest) ProtoMessage() {}

func (x *DeletePaymentWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentWalletRequest.ProtoReflect.Descriptor instead.
func (*DeletePaymentWalletRequest) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePaymentWalletRequest) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

type PaymentWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *PaymentWallet         `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentWalletResponse) Reset() {
	*x = PaymentWalletResponse{}
	mi := &file_payment_wallet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentWalletResponse) ProtoMessage() {}

func (x *PaymentWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_wallet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentWalletResponse.ProtoReflect.Descriptor instead.
func (*PaymentWalletResponse) Descriptor() ([]byte, []int) {
	return file_payment_wallet_proto_rawDescGZIP(), []int{8}
}

func (x *PaymentWalletResponse) GetWallet() *PaymentWallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

var File_payment_wallet_proto protoreflect.FileDescriptor

const file_payment_wallet_proto_rawDesc = "" +
	"\n" +
	"\x14payment_wallet.proto\x12\rpaymentwallet\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x01\n" +
	"\rPaymentWallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\anetwork\x18\x02 \x01(\tR\anetwork\x12%\n" +
	"\x0ewallet_address\x18\x03 \x01(\tR\rwalletAddress\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"]\n" +
	"\x1aCreatePaymentWalletRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\"7\n" +
	"\x1bDeletePaymentWalletResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x1b\n" +
	"\x19ListPaymentWalletsRequest\"T\n" +
	"\x1aListPaymentWalletsResponse\x126\n" +
	"\awallets\x18\x01 \x03(\v2\x1c.paymentwallet.PaymentWalletR\awallets\"]\n" +
	"\x1aUpdatePaymentWalletRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\"3\n" +
	"\x17GetPaymentWalletRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\"6\n" +
	"\x1aDeletePaymentWalletRequest\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\"M\n" +
	"\x15PaymentWalletResponse\x124\n" +
	"\x06wallet\x18\x01 \x01(\v2\x1c.paymentwallet.PaymentWalletR\x06wallet2\xdc\x05\n" +
	"\x14PaymentWalletService\x12\x86\x01\n" +
	"\x13CreatePaymentWallet\x12).paymentwallet.CreatePaymentWalletRequest\x1a$.paymentwallet.PaymentWalletResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/payment-wallets\x12\x86\x01\n" +
	"\x12ListPaymentWallets\x12(.paymentwallet.ListPaymentWalletsRequest\x1a).paymentwallet.ListPaymentWalletsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/payment-wallets\x12\x88\x01\n" +
	"\x11GetPaymentWallets\x12&.paymentwallet.GetPaymentWalletRequest\x1a$.paymentwallet.PaymentWalletResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/v1/payment-wallets/{network}\x12\x90\x01\n" +
	"\x13UpdatePaymentWallet\x12).paymentwallet.UpdatePaymentWalletRequest\x1a$.paymentwallet.PaymentWalletResponse\"(\x82\xd3\xe4\x93\x02\":\x01*\x1a\x1d/v1/payment-wallets/{network}\x12\x93\x01\n" +
	"\x13DeletePaymentWallet\x12).paymentwallet.DeletePaymentWalletRequest\x1a*.paymentwallet.DeletePaymentWalletResponse\"%\x82\xd3\xe4\x93\x02\x1f*\x1d/v1/payment-wallets/{network}B-Z+e-commerce-microservice/proto-shared/gen/pbb\x06proto3"

var (
	file_payment_wallet_proto_rawDescOnce sync.Once
	file_payment_wallet_proto_rawDescData []byte
)

func file_payment_wallet_proto_rawDescGZIP() []byte {
	file_payment_wallet_proto_rawDescOnce.Do(func() {
		file_payment_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_wallet_proto_rawDesc), len(file_payment_wallet_proto_rawDesc)))
	})
	return file_payment_wallet_proto_rawDescData
}

var file_payment_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_payment_wallet_proto_goTypes = []any{
	(*PaymentWallet)(nil),               // 0: paymentwallet.PaymentWallet
	(*CreatePaymentWalletRequest)(nil),  // 1: paymentwallet.CreatePaymentWalletRequest
	(*DeletePaymentWalletResponse)(nil), // 2: paymentwallet.DeletePaymentWalletResponse
	(*ListPaymentWalletsRequest)(nil),   // 3: paymentwallet.ListPaymentWalletsRequest
	(*ListPaymentWalletsResponse)(nil),  // 4: paymentwallet.ListPaymentWalletsResponse
	(*UpdatePaymentWalletRequest)(nil),  // 5: paymentwallet.UpdatePaymentWalletRequest
	(*GetPaymentWalletRequest)(nil),     // 6: paymentwallet.GetPaymentWalletRequest
	(*DeletePaymentWalletRequest)(nil),  // 7: paymentwallet.DeletePaymentWalletRequest
	(*PaymentWalletResponse)(nil),       // 8: paymentwallet.PaymentWalletResponse
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_payment_wallet_proto_depIdxs = []int32{
	9, // 0: paymentwallet.PaymentWallet.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: paymentwallet.ListPaymentWalletsResponse.wallets:type_name -> paymentwallet.PaymentWallet
	0, // 2: paymentwallet.PaymentWalletResponse.wallet:type_name -> paymentwallet.PaymentWallet
	1, // 3: paymentwallet.PaymentWalletService.CreatePaymentWallet:input_type -> paymentwallet.CreatePaymentWalletRequest
	3, // 4: paymentwallet.PaymentWalletService.ListPaymentWallets:input_type -> paymentwallet.ListPaymentWalletsRequest
	6, // 5: paymentwallet.PaymentWalletService.GetPaymentWallets:input_type -> paymentwallet.GetPaymentWalletRequest
	5, // 6: paymentwallet.PaymentWalletService.UpdatePaymentWallet:input_type -> paymentwallet.UpdatePaymentWalletRequest
	7, // 7: paymentwallet.PaymentWalletService.DeletePaymentWallet:input_type -> paymentwallet.DeletePaymentWalletRequest
	8, // 8: paymentwallet.PaymentWalletService.CreatePaymentWallet:output_type -> paymentwallet.PaymentWalletResponse
	4, // 9: paymentwallet.PaymentWalletService.ListPaymentWallets:output_type -> paymentwallet.ListPaymentWalletsResponse
	8, // 10: paymentwallet.PaymentWalletService.GetPaymentWallets:output_type -> paymentwallet.PaymentWalletResponse
	8, // 11: paymentwallet.PaymentWalletService.UpdatePaymentWallet:output_type -> paymentwallet.PaymentWalletResponse
	2, // 12: paymentwallet.PaymentWalletService.DeletePaymentWallet:output_type -> paymentwallet.DeletePaymentWalletResponse
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payment_wallet_proto_init() }
func file_payment_wallet_proto_init() {
	if File_payment_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_wallet_proto_rawDesc), len(file_payment_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_wallet_proto_goTypes,
		DependencyIndexes: file_payment_wallet_proto_depIdxs,
		MessageInfos:      file_payment_wallet_proto_msgTypes,
	}.Build()
	File_payment_wallet_proto = out.File
	file_payment_wallet_proto_goTypes = nil
	file_payment_wallet_proto_depIdxs = nil
}
